name: med_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  provider: ^6.0.5
  path_provider: ^2.1.5
  isar:
      hosted: https://pub.isar-community.dev 
      version: ^3.1.8
  isar_flutter_libs:
      hosted: https://pub.isar-community.dev 
      version: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  isar_generator: 
      hosted: https://pub.isar-community.dev 
      version: ^3.1.8
  build_runner: ^2.4.13
  floor_generator: ^1.5.0
  retrofit_generator: ^9.1.5

flutter:
  uses-material-design: true
